import portfolio from '../../assets/IMG_cowercing_2.jpg'
import shahzodAkajon from '../../assets/shaxzod_akajon.png'
import sayyorbek from '../../assets/xudam-2.png'
import oytem from '../../assets/oytijon.png'
import jaxongirUstoz from '../../assets/Jahongir.jpg'
import ziyo from '../../assets/Ziyo.jpg'
import MuhammadUstoz from '../../assets/Muhammad-ustoz.png'
import mansurUstoz from '../../assets/mansurUstoz.png'
import toshtemirUstoz  from '../../assets/ToshtemirUstozim.png'


export const ustozlar = [

    {
        id: 1,
        name: "Muradov",
        surname: "Shaxzod",
        fullName: "Muradov Shaxzod",
        img: shahzodAkajon,
        kursnomi: 'Frontend',
        tajriba: "+5 yil",
        mamnunOquvchilar: "+50",
        loyihalar: "+15",
        kursUstozi: "Frontend kursi ustozi",
        qoshimchaMalumot: "Frontend dasturchi — bu talab yuqori bo‘lgan kasbFrontend dasturchilar saytlar, xizmatlar va ilovalarni yaratishadi, ulardan millionlab odamlar foydalanadi: internet-do'konlar, onlayn banklar, qidiruv tizimlari, ijtimoiy tarmoqlar. Bunday mutaxassis saytning tashqi ko‘rinishi bilan ham, foydalanuvchilar ko‘rmaydigan xizmat qismi bilan ham ishlashi mumkin.",
        portfolio: portfolio,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '790.000',
        bizningMentorlar: 'Bizning mentorlarimiz xalqaro darajadagi mutaxassislar bo`lib, o`z sohasida katta tajribaga ega. ',
        texnologiyalar: ['HTML', 'CSS', 'Sass', 'Bootstrap', 'JavaScript', 'React', 'Vue.js', 'NPM terminal commands', "Node.js", "GitHub", 'Git', "AI", 'Webpack', "ReduxToolkit", "TypeScript", "Figma", "Responsive Design"],
        
    },
    {
        id: 6,
        name: "Elmurodov",
        surname: "Ziyodulloh",
        fullName: "Elmurodov Ziyodulloh",
        img: ziyo,
        kursNome: ' Kompyuter savotxonligi',
        tajriba: "+2 yil",
        mamnunOquvchilar: "+50",
        kursUstozi: "Kompyuter savodxonligi kursi ustozi",
        // loyihalar: "+10",
        qoshimchaMalumot: "Kompyuter bu - texnologiyalaridan samarali foydalanish va raqamli dunyoda ishlash uchun zarur bo‘lgan bilim va ko‘nikmalarni egallashни anglatadi. Kompyuter savodxonligi har bir shaxs uchun muhim, chunki zamonaviy hayotda kompyuter va internetни qo‘llash barcha sohalarda zarur bo‘lgan asosiy ko‘nikma hisoblanadi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '690.000',
        texnologiyalar: ['Microsoft Office', 'Google Workspace', 'Data Analysis', 'AI', 'excel', 'word', 'powerpoint', 'email communication', 'basic programming concepts'],

    },
    {
        id: 4,
        name: "Hamidov",
        surname: "Jahongir",
        fullName: "Hamidov Jahongir",
        img: jaxongirUstoz,
        kursNomi: 'Design & AI pro',
        tajriba: "+2 yil",
        mamnunOquvchilar: "+50",
        kursUstozi: "Design & AI pro kursi ustozi",
        loyihalar: "+7",
        qoshimchaMalumot: "Vizual kommunikatsiyani yaratish va ma'lumotlarni estetik tarzda taqdim etish san'ati va texnikasidir. Grafik dizaynerlar turli xil vizual elementlarni (ranglar, shakllar, tasvirlar va shriftlar) birlashtirgan holda, ma'lumot yoki g'oyani samarali va chiroyli tarzda ifodalashadi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '740.000',
    },
    {
        id: 5,
        name: "Muradova",
        surname: "Nurona",
        fullName: "Muradova Nurona",
        img: oytem,
        kursNomi: 'SMM',
        tajriba: "+2 yil",
        mamnunOquvchilar: "+30",
        kursUstozi: "SMM kursi ustozi",
        loyihalar: "+5",
        qoshimchaMalumot: "SMM - bu ijtimoiy tarmoqlarda marketing strategiyalarini yaratish va amalga oshirish jarayonidir. SMMning asosiy maqsadi – mahsulot yoki xizmatni targ‘ib qilish, brendni tanitish va maqsadli auditoriya bilan aloqani o‘rnatishdir. ",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '900.000',
        texnologiyalar: ['Facebook Ads', 'Instagram Ads', 'AI', 'Content Creation', 'Analytics Tools', 'ssenaries', "Mobilogrph",]

    },
    {
        id: 3,
        name: "Xoliqov",
        surname: "Sayyorbek",
        fullName: "Xoliqov Sayyorbek",
        img: sayyorbek,
        kursNomi: "Foundation",
        tajriba: "+3 yil",
        mamnunOquvchilar: "+50",
        kursUstozi: "Foundation kursi ustozi",
        loyihalar: "+5",
        qoshimchaMalumot: "Foundation - dasturlashni noldan o‘rganmoqchi bo‘lganlar uchun maxsus ishlab chiqilgan boshlang‘ich kurs bo‘lib, u IT sohasiga birinchi qadam qo‘yish uchun mustahkam poydevor yaratadi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '740.000',
        texnologiyalar: ['c#', 'C++', 'Python', 'GitHub', 'AI', "Algaritmlash", "Ma`lumotlar tuzilmasi", "Muammolarni yechish",
            "Xatoliklar ustida ishlash",
        ],

    },
    {
        id: 7,
        name: "G`ulomhusinov",
        surname: "Muhammad",
        fullName: "G`ulomhusinov Muhammadmuso",
        img: MuhammadUstoz,
        kursNomi: 'Backend',
        tajriba: "+3 yil",
        mamnunOquvchilar: "+50",
        kursUstozi: "Backend kursi ustozi",
        loyihalar: "+5",
        qoshimchaMalumot: "Backend - veb-ilovalar va saytlarning server tomonidagi ishlarni boshqaradigan dasturlash sohasi. Backend dasturchilari foydalanuvchilarga ko‘rinmaydigan, ammo veb-sayt yoki ilovaning ishlashini ta’minlaydigan barcha tizimlarni yaratadi. Ular server, ma'lumotlar bazasi va ilovaning mantiqiy qismlari bilan ishlashadi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '840.000',
        texnologiyalar: ['Node.js', 'Express.js', 'MongoDB', 'PostgreSQL', 'AI', 'Terminal Commands', "Django"],
    },
    {
        id: 8,
        name: "Abdurahmonov",
        surname: "Toshtemir",
        fullName: "Abdurahmonov Toshtemir",
        img: toshtemirUstoz,
        kursNomi: 'Robototexnika',
        tajriba: "+3 yil",
        mamnunOquvchilar: "+60",
        kursUstozi: "Robototexnika kursi ustozi",
        loyihalar: "+5",
        qoshimchaMalumot: "Robototexnika - bu robototexnika sohasida yuqori darajadagi bilim va ko‘nikmalarni egallashni maqsad qilgan professional kursdir. Kurs davomida talabalarga murakkab robototexnika tizimlarini yaratish, sun’iy intellekt va mashina o‘rganish kabi ilg‘or texnologiyalarni robotlarga integratsiya qilish, shuningdek, avtomatizatsiya va IoT (Internet of Things) tizimlari bilan ishlash o‘rgatiladi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '990.000',
        texnologiyalar: ['Python', 'C++', 'AI', 'Robotics Fundamentals', 'Control Systems', "ROS", "OpenCV", "Arduino", "Raspberry Pi"],

    },
    {
        id: 8,
        name: "Hamidov",
        surname: "Mansur",
        fullName: "Hamidov Mansur", 
        img: mansurUstoz,
        kursNome: ' Kompyuter savotxonligi',
        tajriba: "+4 yil",
        mamnunOquvchilar: "+70",
        kursUstozi: "Kompyuter savodxonligi kursi ustozi",
        // loyihalar: "+10",
        qoshimchaMalumot: "Kompyuter bu - texnologiyalaridan samarali foydalanish va raqamli dunyoda ishlash uchun zarur bo‘lgan bilim va ko‘nikmalarni egallashни anglatadi. Kompyuter savodxonligi har bir shaxs uchun muhim, chunki zamonaviy hayotda kompyuter va internetни qo‘llash barcha sohalarda zarur bo‘lgan asosiy ko‘nikma hisoblanadi.",
        // portfolio: portfolio ,
        nechaSoat: '2',
        haftada: '3',
        kursNarxi: '690.000',
        texnologiyalar: ['Microsoft Office', 'Google Workspace', 'Data Analysis', 'AI', 'excel', 'word', 'powerpoint', 'email communication', 'basic programming concepts'],

    },
    

]